### ISSUE TITLE
Removing unused branches 

### ISSUE THREAD

**Issue by atishelmanch** [CMS-ECAL-Trigger-Group/ETTAnalyzer#5]
Hello @ramankhurana @valsdav - I'm cleaning up this repo by removing stale / unused branches, and archiving them as releases just in case they end up being useful in the future. Do you think there is any functionality in the following branches which should be merged to `main`? 

[CMSSW_11_0_2-OddWeightsDev](https://github.com/CMS-ECAL-Trigger-Group/ETTAnalyzer/tree/CMSSW_11_0_2-OddWeightsDev)
[CMSSW_11_1_4](https://github.com/CMS-ECAL-Trigger-Group/ETTAnalyzer/tree/CMSSW_11_1_4)
[CMSSW_11_0_2](https://github.com/CMS-ECAL-Trigger-Group/ETTAnalyzer/tree/CMSSW_11_0_2) 
[CMSSW_11_3_0_ETTAnalyzerdev](https://github.com/CMS-ECAL-Trigger-Group/ETTAnalyzer/tree/CMSSW_11_3_0_ETTAnalyzerdev)
[cond_from_db_tags](https://github.com/CMS-ECAL-Trigger-Group/ETTAnalyzer/tree/cond_from_db_tags)

If not, can I go ahead and save these as releases so that I can delete the branches? (please let me know if there's a more ideal way to archive these). Thank you.

**Comment by ramankhurana** [comment]
Hi Abe, Sure please go ahead, all the changes related to 5BX are still in my local area, I will push once I am happy with it, 

Thanks for cleaning this up.

**Comment by atishelmanch** [comment]
Great - thanks!

**Comment by atishelmanch** [comment]
Done - nice and clean 🧹
